spring:
  application:
    name: eurekaclient-producer
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/

server:
  port: 9091

management:
  endpoints:
    web:
      exposure:
        include: ["hystrix", "hystrix.stream"]
