server:
  port: 9095
spring:
  application:
    name: feign-client


#### eureka client ÅäÖÃ
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/


### feign ÅäÖÃ
  ## feign ¶ÏÂ·Æ÷
feign:
  hystrix:
    enabled: true
